### ISSUE TITLE
Modularity in sgd.R

### ISSUE THREAD

**Issue by dustinvtran** [dustinvtran/ai-sgd#14]
I've been tweaking `sgd.R` over the past few days and it has gotten absurdly lengthy (have not pushed the latest yet).

It would be natural to use update functions, e.g., in the main loop, you would have something such as `theta.new <- sgd.update(...)` for each if statement. However, the number of parameters the update function takes causes them to be very convoluted.

Here's an example of what the main loop would look like:
```r
# Run the stochastic gradient method.
# Main iteration: i = #iteration
for (i in 1:(n*npass)) {
  # Update y matrix if method uses least squares estimate.
  if (sgd.method %in% c("LS-SGD", "LS-ISGD")) {
    y[, i] <- ls.update(i, data, theta.sgd, n)
  }
  # Update parameters.
  if (sgd.method %in% c("SGD", "ASGD", "LS-SGD")) {
    theta.new <- sgd.update(i, data, theta.sgd, lr, lambda, n, ...)
  } else if (sgd.method %in% c("ISGD", "AI-SGD", "LS-ISGD")) {
    theta.new <- isgd.update(i, data, theta.sgd, lr, lambda, n, ...)
  } else if (sgd.method == "SVRG") {
    theta.new <- svrg.update(i, data, theta.sgd, lr, lambda, n, ...)
  }
  theta.sgd[, i+1] <- theta.new
}
```

Is this an acceptable solution? It makes the `sgd()` function more readable at the cost of making the update functions themselves a bit convoluted.

**Comment by ptoulis** [comment]
I think its fine as long as the functionality is the same, and also the there is no big hit computationally.

**Comment by dustinvtran** [comment]
Okay, I'm finally able to get comparable speeds. I did a few benchmarks using the new `sgd()` in 958e3b739832c5b2fe3f668d640479496fc75f32 compared to the old `sgd()` in c670ad4f6932cb1adbb697494da2125306b92754. `run.new()` is the `run()` function using the new `sgd()` and `run.old()` uses the old `sgd()`. Surprisingly I was able to reach even faster speeds; this is probably caused by some efficiency gain I did during the conversion, although I couldn't glean what this is from a diff.

```r
library(microbenchmark)
pars <- rbind(c(0.001,0), c(0.005, 0))
microbenchmark(run.new("gaussian", pars=pars, n=1e4, p=1e2, add.methods="SGD"),
 run.old("gaussian", pars=pars, n=1e4, p=1e2, add.methods="SGD"), times=5L)
## Unit: seconds
##                                                                       expr
##  run.new("gaussian", pars = pars, n = 10000, p = 100, add.methods = "SGD")
##  run.old("gaussian", pars = pars, n = 10000, p = 100, add.methods = "SGD")
##       min       lq     mean   median       uq      max neval
##  3.602843 3.606303 3.717455 3.634098 3.715109 4.028922     5
##  7.354212 7.799453 7.919585 7.904100 8.001440 8.538721     5
```
